### ISSUE TITLE
Is the original sequencing data released yet?

### ISSUE THREAD

**Issue by pants08** [Shuhua-Group/Chinese-Pangenome-Consortium-Phase-I#2]
Hi there!
Is the original sequencing data like hifi or hic data of those samples in this article released yet?(A Pangenome Reference of 36 Chinese populations, 13 October 2022, PREPRINT (Version 1) available at Research Square, DOI: [10.21203/rs.3.rs-2097264/v1]) 
Could they or when shall they be released? 
Cause I found only the pangenome reference available in this repository,which doesn't work for me.

Thanks in advance!

**Comment by TanXinjiang** [comment]
Sorry for not responding in time. You can get access to the assemblies at the National Genomics Data Center (https://ngdc.cncb.ac.cn/) under the BioProject PRJCA011422.
