### ISSUE TITLE
Missing links to download the `Haplotype-resolved assemblies generated by hifiasm`

### ISSUE THREAD

**Issue by AndreaGuarracino** [Shuhua-Group/Chinese-Pangenome-Consortium-Phase-I#7]
Hi, the README reports that in the `files` directory there should be links to obtain all the assemblies (57) in FASTA format, but the current `files` folder contains just an empty `README.md`.

Would you please provide an easy way to download the assemblies? Also a single, compressed `.fasta.gz` would be fine.

**Comment by TanXinjiang** [comment]
Hi, you can get acess to the assemblies of 57 samples at https://ngdc.cncb.ac.cn/search/?dbId=gwh&q=PRJCA011422 and 10 samples at https://ngdc.cncb.ac.cn/search/?dbId=hra&q=PRJCA011461
